export const actionTypes = {
    LOCATIONS_UPDATE_DATE: 'LOCATIONS_UPDATE_DATE',
    LOCATIONS_UPDATE_DATE_SUCCESS: 'LOCATIONS_UPDATE_DATE_SUCCESS',

    LOCATIONS_LOAD_LIST: 'LOCATIONS_LOAD_LIST',
    LOCATIONS_LOAD_LIST_SUCCESS: 'LOCATIONS_LOAD_LIST_SUCCESS',
};
