export const actionTypes = {
    PRODUCTS_REQUEST_NEWS: 'PRODUCTS_REQUEST_NEWS',
    PRODUCTS_REQUEST_NEWS_SUCCESS: 'PRODUCTS_REQUEST_NEWS_SUCCESS',

    PRODUCTS_INCREMENT_COUNTER: 'PRODUCTS_INCREMENT_COUNTER',
    PRODUCTS_INCREMENT_COUNTER_SUCCESS: 'PRODUCTS_INCREMENT_COUNTER_SUCCESS',

    PRODUCTS_LOAD_LIST: 'PRODUCTS_LOAD_LIST',
    PRODUCTS_LOAD_LIST_SUCCESS: 'PRODUCTS_LOAD_LIST_SUCCESS'
};
